# Generated by Django 5.0.1 on 2024-01-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list_base', '0002_remove_recipe_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
