# Generated by Django 5.0.1 on 2024-01-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list_base', '0003_alter_recipe_options_recipe_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe_list_base_recipe',
        ),
    ]
